---
title: "plot_beast_trees"
author: "DV"
date: "2/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls()) 
```

```{r}
library(ggplot2)
library(ggtree)
library(tidyr)
library(ape)
library(phytools)
```

```{r}
HAtree <- read.tree("./data/swhu-fludb-map-mauto-muscle-trim-fasttree.tre")
midHAtree <- midpoint.root(HAtree)
```

```{r}
dd <-  read.delim("./data/annotations-v2.txt", strip.white = T, sep = "\t")


dd$global_sw_clade <- as.character(dd$global_sw_clade)
dd$global_sw_clade[is.na(dd$global_sw_clade)] <- "not_available"
unique(dd$global_sw_clade)


library(dplyr)
dd <- dd %>% mutate(simplelin = case_when(
  startsWith(global_sw_clade, "1A") ~ "1A",
  startsWith(global_sw_clade, "1B") ~ "1B",
  startsWith(global_sw_clade, "1C") ~ "1C",
  startsWith(global_sw_clade, "not_") ~ "not_available",
  startsWith(global_sw_clade, "Other_Human") ~ "1B-like",
  startsWith(global_sw_clade, "Other_Avian") ~ "Avian",
  startsWith(global_sw_clade, "na") ~ "not_available",
  TRUE ~ "Others"))


dd$host <- gsub("hu-variant", "swine-variant", dd$host)
dd$host <- gsub("hu-seasonal", "human", dd$host)
dd$host <- gsub("hu-vaccine", "human-vaccine", dd$host)

unique(dd$source)

dd$source <- factor(dd$source, levels =c("map", "fludb"))

scols <- c("map" = "blue",
           "fludb" = "gray")

dd$new_global_lineage[is.na(dd$new_global_lineage)] <- "not_available"
unique(dd$new_global_lineage)
```

#£ set colours - lineages

```{r}

H1_palette = c(
 # "1A.1"="#800080",
 # "1A.1-like"="#800080", #added by DV
 # "1A.1.1"="#0099CC", # multiple clade names can map to same hex color
 # "1A.1.1" = "#0099CC",
  "1A.1.1-1" = "#0099CC",
  "1A.1.1-2" = "#568899",
  "1A.1.1-3" = "#0e5a73",
  #"alpha"="#0099CC",  # ergo can add both global and us lineage names as needed
 # "1A.1.2"="#33FFFF",  
 # "1A.1.3"="#6666FF", 
  "1A.2"="#CCCCFF",
  #"beta"="#CCCCFF",    
  #"1A.3"="#FF99FF",
  "1A.3.1"="#8000FF",
  "1A.2-3-like"="#8000FF", #added by DV
  #"gamma2-beta-like"="#8000FF",
  "1A.3.2"="#FF33FF",
  #"gamma2"="#FF33FF",
 # "1A.3.3"="#CC00CC",
  #"1A.3.3.1"="#004080",
  "1A.3.3.2"="#330066",
  #"pandemic"="#330066",
  "1A.3.3.3"="#3300FF",
 # "gamma"="#3300FF",
 # "Human"="#999999",
 # "1B.1"="#FF9999",
  #"1B.1.1"="#CC0033",
 # "1B.1.2"="#FF66CC",
 # "1B.1.2.1"="#B2478E",
 # "1B.1.2.2"="#FF3300",
 # "1B.1.2.3"="#FF9933",
  #"1B.2"="#996633",
  "Other_Human_1B.2"="#996633",
  "1B.2.1"="#CC9900",
 # "delta2"="#CC9900",
  "1B.2.2"="#C48945",
 # "delta1"="#C48945",
  "1B.2.2.1"="#990066",
  #"delta1a"="#990066",
  "1B.2.2.2"="#FF6666",
 # "delta1b"="#FF6666",
  #"Avian"="#666666",
 # "1C.1"="#00FF00",
 # "1C.2"="#12AD2A",
 # "1C.2.1"="#B9FF4D",
 # "1C.2.2"="#006600",
 # "1C.2.3"="#0FF591",
  #"Vaccine"="#333333",
  "Human"="#333333"
  #"Other_Human"="#CC0000",
 #"NA"="grey"
  #"human"="#999999"
)
```

```{r}
pdf(file = "figures/sw-hu-map-sep2022-nodenums.pdf", 
    #res = 300,
    height = 60,
    width = 60)#,
    #pointsize = 14)

p_nodes <-  ggtree(midHAtree) 
p_nodes <- p_nodes %<+% dd +
  geom_point2(aes(subset= !is.na(label) & label > 99.5), shape=18, size=1) +
  geom_tiplab(aes(color = new_global_lineage), size =3, offset = 0.02) +
  geom_tippoint(aes(color = new_global_lineage), size = 1.2) +
  geom_text2(aes(subset=!isTip, label=node, hjust=1, vjust=-0.6, size=2)) + 
  geom_cladelabel(node=680, label="pandemic (1A.3.3.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=571, label="gamma (1A.3.3.3)", align=T,  offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=783, label="beta (1A.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=832, label="alpha (1A.1.1-1)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=856, label="alpha (1A.1.1-3)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=854, label="alpha (1A.1.1-2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=975, label="delta1 (1B.2.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=917, label="delta2 (1B.2.1)", align=T, offset.text = 0.06, offset = 1.2) +
  scale_color_manual(values =H1_palette) +
  geom_treescale(x = 3) + 
  #ggtitle("Figure S1B ") +
  theme(legend.position="right",
        text = element_text(size =18)) +
  guides(color = guide_legend(override.aes = list(size = 5)))
  
p_nodes
 



dev.off()

  
         
```

```{r}

png(filename = "./figures/Figure_S1B_sw-hu-map-host.png", 
    res = 300,
    height = 14*300,
    width = 8*300,
    pointsize = 14)


p1 <-  ggtree(midHAtree) + xlim(NA, 4) 
p1 <- p1 %<+% dd +
  geom_point2(aes(subset= !is.na(label) & label > 99.5), shape=18, size=1) +
  geom_tiplab(aes(color = host), size =0.8, offset = 0.05) +
  geom_tippoint(aes(color = host), size = 1.2) +
  geom_cladelabel(node=680, label="pandemic (1A.3.3.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=571, label="gamma (1A.3.3.3)", align=T,  offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=783, label="beta (1A.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=832, label="alpha (1A.1.1-1)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=856, label="alpha (1A.1.1-3)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=854, label="alpha (1A.1.1-2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=975, label="delta1 (1B.2.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=917, label="delta2 (1B.2.1)", align=T, offset.text = 0.06, offset = 1.2) +
  scale_color_brewer(palette = "Set1") +
  geom_treescale(x = 3) + 
  ggtitle("Figure S1B") +
  theme(legend.position="right",
        text = element_text(size =18)) +
  guides(color = guide_legend(override.aes = list(size = 5)))
  
p1
 
dev.off()
  
         
```

```{r}
png(filename = "./figures/Figure_S1A_sw-hu-map-country.png", 
    res = 300,
    height = 14*300,
    width = 8*300,
    pointsize = 14)


p1 <-  ggtree(midHAtree) + xlim(NA, 4) 

p1 <- p1 %<+% dd +
  geom_point2(aes(subset= !is.na(label) & label > 99.5), shape=18, size=1) +
  geom_tiplab(aes(color = country), size =0.8, offset = 0.05) +
  geom_tippoint(aes(color = country), size = 1.2) +
  geom_cladelabel(node=680, label="pandemic (1A.3.3.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=571, label="gamma (1A.3.3.3)", align=T,  offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=783, label="beta (1A.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=832, label="alpha (1A.1.1-1)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=856, label="alpha (1A.1.1-3)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=854, label="alpha (1A.1.1-2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=975, label="delta1 (1B.2.2)", align=T, offset.text = 0.06, offset = 1.2) +
  geom_cladelabel(node=917, label="delta2 (1B.2.1)", align=T, offset.text = 0.06, offset = 1.2) +
  scale_color_brewer(palette = "Dark2") +
  geom_treescale(x = 3) + 
  ggtitle("Figure S1A") +
  theme(legend.position="right",
        text = element_text(size =18)) +
  guides(color = guide_legend(override.aes = list(size = 5)))
  
p1
 
dev.off()
```
