---
title: "plotML_swineNAm"
author: "DV"
date: "2020-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls()) 
```

```{r}
library(ggplot2)
library(ggtree)
library(tidyr)
library(ape)
require(gridExtra)
library(ggpubr)
```



```{r}
HAtree <- read.tree("db0.98-map-mauto.tre")

library(phytools)

HAmidtree <- midpoint.root(HAtree)
HAmidtree <- drop.tip(HAmidtree,"map|swine|EU139826|H1N1|alpha|A/SWINE/IOWA/1973")
HAmidtree <- drop.tip(HAmidtree,"bg|KU976737|A/swine/Mexico/AVX47/2013|Mexico|2013-01-08")



dd <-  read.delim("annotations4.1.txt", strip.white = T, sep = "\t" )
```

#set factor levels and colours - origin, source
```{r}

dd$country <- factor(dd$country, levels = c("Canada", 
                                          "Mexico",
                                          "USA"))

cols <- c("Canada" = "#d46180", 
          "Mexico" = "#7ed160", 
          "USA" = "#609cd1")

dd$source <- gsub(x = dd$source, pattern = "map", replacement = "used in HI assay", fixed = T)
dd$source <- gsub(x = dd$source, pattern = "bg", replacement = "genbank", fixed = T)
dd$source <- factor(dd$source, levels =c("used in HI assay", "genbank"))

scols <- c("used in HI assay" = "blue",
           "genbank" = "gray")

dd$host <- gsub(x = dd$host, pattern = "sw_to_human", replacement = "human variant", fixed = T)
```

#set colours - lineages

```{r}

lcols = c(
  "1A.1"="#800080",
  "1A.1-like"="#800080", #added by DV
  "1A.1.1"="#0099CC", # multiple clade names can map to same hex color
  "alpha"="#0099CC",  # ergo can add both global and us lineage names as needed
  "1A.1.2"="#33FFFF",  
  "1A.1.3"="#6666FF", 
  "1A.2"="#CCCCFF",
  "beta"="#CCCCFF",    
  "1A.3"="#FF99FF",
  "1A.3.1"="#8000FF",
  "1A.2-3-like"="#8000FF", #added by DV
  "gamma2-beta-like"="#8000FF",
  "1A.3.2"="#FF33FF",
  "gamma2"="#FF33FF",
  "1A.3.3"="#CC00CC",
  "1A.3.3.1"="#004080",
  "1A.3.3.2"="#330066",
  "pandemic"="#330066",
  "1A.3.3.3"="#3300FF",
  "gamma"="#3300FF",
  "Human"="#999999",
  "1B.1"="#FF9999",
  "1B.1.1"="#CC0033",
  "1B.1.2"="#FF66CC",
  "1B.1.2.1"="#B2478E",
  "1B.1.2.2"="#FF3300",
  "1B.1.2.3"="#FF9933",
  "1B.2"="#996633",
  "Other-Human-1B.2"="#996633",
  "1B.2.1"="#CC9900",
  "delta2"="#CC9900",
  "1B.2.2"="#C48945",
  "delta1"="#C48945",
  "1B.2.2.1"="#990066",
  "delta1a"="#990066",
  "1B.2.2.2"="#FF6666",
  "delta1b"="#FF6666",
  "Avian"="#666666",
  "1C.1"="#00FF00",
  "1C.2"="#12AD2A",
  "1C.2.1"="#B9FF4D",
  "1C.2.2"="#006600",
  "1C.2.3"="#0FF591",
  "Vaccine"="#333333",
  "Other_Human"="#CC0000",
  "human"="#999999"
)
```


#testing-get node nums

```{r}

png(filename = "figures/HA-H1iqtree-nodenums.png", 
    res = 300,
    height = 12*300,
    width = 8*300,
    pointsize = 11)

(p1 <-  ggtree(HAmidtree, right = T) %<+% dd +
  #geom_point2(aes(subset= !is.na(node.label) & label > 85), shape=18, size=2.5) +
  geom_tippoint(aes(color = global_lineage), size = 2) +
  scale_color_manual(values = lcols) +
  #scale_color_manual(values = cols) +
  #scale_color_brewer(palette = "Set1") +
  geom_cladelabel(node=678, label="gamma (1A.3.3.3)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=773, label="pandemic (1A.3.3.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=842, label="beta (1A.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=620, label="alpha (1A.1.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=494, label="delta1 (1B.2.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=444, label="delta2 (1B.2.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  #geom_text2(aes(subset= (node == 440),label="1B"), hjust=1.2, vjust=-1.0, size = 5) +
  #geom_text2(aes(subset= (node == 611),label="1A"), hjust=1.2, vjust=-1.0, size = 5) +
  geom_text2(aes(subset = !isTip, label = node, hjust = 1.2, vjust = -0.8)) +
  geom_treescale(offset = 2, y = -3) + 
  ggtitle("HA H1 nodenumbers") +
  theme(legend.position="right",
        text = element_text(size =14)))
  

 
dev.off()
  
         
```



#H1 tree by origin
```{r}
png(filename = "figures/H1swineNAm2012-19_byorigin.png", 
    res = 300,
    height = 11.69*300,
    width = 8.27*300,
    pointsize = 12)

(p2 <-  ggtree(HAmidtree, right = T) %<+% dd +
  geom_nodepoint(aes(subset = label >0.80), shape = 18, size =2) +
  #geom_point2(aes(subset= !is.na(HAtree$node.label) & HAtree$node.label > 85), shape=18, size=2.5) +
  geom_tippoint(aes(color = country), size = 2.5) +
  scale_color_manual(values = cols) +
  #geom_text2(aes(subset = (isTip & source == "map"),label = "        *"), ,hjust=-0.02, size=12) +
  geom_cladelabel(node=678, label="gamma (1A.3.3.3)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=773, label="pandemic (1A.3.3.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=842, label="beta (1A.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=620, label="alpha (1A.1.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=494, label="delta1 (1B.2.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=444, label="delta2 (1B.2.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_text2(aes(subset= (node == 440),label="1B"), hjust=1.2, vjust=-0.1, size = 6) +
  geom_text2(aes(subset= (node == 611),label="1A"), hjust=1.2, vjust=-0.4, size = 6) +
  geom_treescale(offset = 2, y = -3, fontsize = 4) + 
  #ggtitle("Swine H1 HA North America (2012-2019)") +
  theme(legend.position="right",
        text = element_text(size = 16)) +
  labs(color = "Country")) 
  
 
#ggsave(plot = p2, "figures/Fig1_H1swineNAm2012-19_byorigin.pdf", dpi=300, width=8.27, height=11.69)

dev.off()
```

# H1 tree by source
```{r}
png(filename = "./figures/Fig1_H1swineNAm2012-19_bysource.png", 
    res = 300,
    height = 11.69*300,
    width = 8.27*300,
    pointsize = 12)

(p3 <-  ggtree(HAmidtree, right = T) %<+% dd +
  geom_nodepoint(aes(subset = label >0.80), shape = 18, size =2) +
  #geom_point2(aes(subset= !is.na(HAtree$node.label) & HAtree$node.label > 85), shape=18, size=2.5) +
  geom_tippoint(aes(color = source), size = 2.5) +
  scale_color_manual(values = scols) +
  #geom_text2(aes(subset = (isTip & source == "map"),label = "        *"), ,hjust=-0.02, size=12) +
  geom_cladelabel(node=678, label="gamma (1A.3.3.3)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=773, label="pandemic (1A.3.3.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=842, label="beta (1A.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=620, label="alpha (1A.1.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=494, label="delta1 (1B.2.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=444, label="delta2 (1B.2.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_text2(aes(subset= (node == 440),label="1B"), hjust=1.2, vjust=-0.1, size = 6) +
  geom_text2(aes(subset= (node == 611),label="1A"), hjust=1.2, vjust=-0.4, size = 6) +
  geom_treescale(offset = 2, y = -3, fontsize = 4) + 
  #ggtitle("Swine H1 HA North America (2012-2019)") +
  theme(legend.position="right",
        text = element_text(size = 16)) +
  labs(color = "")) 
  
 
#ggsave(plot = p3, "./figures/Fig1_H1swineNAm2012-19_bysource.pdf", dpi=300, width=8.27, height=11.69)

dev.off()

#how to collapse a node
#p2<- collapse(p2, node=613, clade_name = "1A") 
```


# H1 tree by lineage

```{r}
png(filename = "./figures/Fig1_H1swineNAm2012-19_bylineage.png", 
    res = 300,
    height = 11.69*300,
    width = 8.27*300,
    pointsize = 12)

(p4 <-  ggtree(HAmidtree, right = T) %<+% dd +
  geom_nodepoint(aes(subset = label >0.80), shape = 18, size =2) +
  #geom_point2(aes(subset= !is.na(HAtree$node.label) & HAtree$node.label > 85), shape=18, size=2.5) +
  geom_tippoint(aes(color = global_lineage), size = 2.5) +
  scale_color_manual(values =lcols) +
  #geom_text2(aes(subset = (isTip & source == "map"),label = "        *"), ,hjust=-0.02, size=12) +
  geom_cladelabel(node=678, label="gamma (1A.3.3.3)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=773, label="pandemic (1A.3.3.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=842, label="beta (1A.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=620, label="alpha (1A.1.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=494, label="delta1 (1B.2.2)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_cladelabel(node=444, label="delta2 (1B.2.1)", align=T, angle=270, hjust='center', offset.text = 0.005) +
  geom_text2(aes(subset= (node == 440),label="1B"), hjust=1.2, vjust=-0.1, size = 6) +
  geom_text2(aes(subset= (node == 611),label="1A"), hjust=1.2, vjust=-0.4, size = 6) +
  geom_treescale(offset = 2, y = -3, fontsize = 4) + 
  #ggtitle("Swine H1 HA North America (2012-2019)") +
  theme(legend.position="right",
        text = element_text(size = 16)) +
  labs(color = "Lineage")) 
  
 
#ggsave(plot = p4, "./figures/Fig1_H1swineNAm2012-19_bylineage.pdf", dpi=300, width=8.27, height=11.69)

dev.off()

```
#alpha -dels
```{r}
png(filename = "figures/HA-H1iqtree_alphadel.png", 
    res = 300,
    height = 18*300,
    width = 14*300,
    pointsize = 14)

p5 <-  ggtree(HAmidtree, right = T) 
#p12<- collapse(p2, node=613, clade_name = "1A")

p5 <- p5 %<+% dd +
  geom_nodepoint(aes(subset = label >0.80), shape = 18, size =3) +
  #geom_point2(aes(subset= !is.na(HAtree$node.label) & HAtree$node.label > 85), shape=18, size=2.5) +
  geom_tippoint(aes(color = isalphadel), size = 3) +
  #scale_color_manual(values = cols) +
  #scale_color_manual(values = scols) +
  #scale_color_manual(values = lcols) +
  scale_color_brewer(palette = "Set1") + 
  #geom_text2(aes(subset = !isTip, label = node, hjust = 1.2, vjust = -0.8, size = 2)) +
  #geom_text2(aes(subset= (node == 856),label="alpha"), hjust=1.2, vjust=-1.0, size=10) +
  
  ##geom_text2(aes(subset= (node == 802),label="alpha"), hjust=1.2, vjust=-1.0, size=9) +
  ##geom_text2(aes(subset= (node == 784),label="beta"), hjust=1.2, vjust=-1.0, size=9) +
  ##geom_text2(aes(subset= (node == 620),label="gamma"), hjust=1.2, vjust=-0.8, size=9) +
  ##geom_text2(aes(subset= (node == 715),label="npdm"), hjust=1.2, vjust=-0.5, size=9) +
  ##geom_text2(aes(subset= (node == 618),label="gamma-npdm"), hjust=1.2, vjust=-1.0, size=9) +
  ##geom_text2(aes(subset = (node == 488),label="delta1"), hjust=1.0, vjust=-1.0, size=9) +
  ##geom_text2(aes(subset = (node == 440),label="delta2"), hjust=1.0, vjust=1.0, size=9) +
  ##geom_text2(aes(subset = (node == 613),label="1A"), hjust=1.2, vjust=1.2, size=10) +
  ##geom_text2(aes(subset = (node == 434),label="1B"), hjust=1.2, vjust=1.2, size=10) +
  
  geom_text2(aes(subset = (isTip & source == "map"),label = "...................in map"), hjust=-0.02, size=3) +
  geom_treescale(offset = 2, y = -3, fontsize = 9) + 
  ggtitle("H1 HA (2012-2018)") +
  theme(legend.position="right",
        text = element_text(size =38)) +
  labs(color = "Lineage")
  
p5
 
dev.off()

```





