---
title: "PlotAntigenicDistances H1"
author: "DV, JC"
date: "02/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ===== Initial Variables
rm(list = ls())

infile="merge_v3_2012-18_reduced-alldistances.csv"


# ===== libraries
library(ggplot2)
library(readr)       # faster and less error prone than read.csv
library(readxl)      # for people who prefer to load excel files, avoid tsv conversion confusion and bugs
library(tidyverse)   # clean data

```

## Read in the distances and clean data

```{r}
# ===== Data loading and cleaning

dat <- read_delim(infile,delim=",",na=c("n/a"))

AGs1 <- grep("AG", dat$No1)

dat <- dat[AGs1,]

AGs2 <- grep("AG", dat$No2)

dat <- dat[AGs2,]

```

```{r}
# ===== Identify non swine strains - human vaccine bin them under "huvac"

huvac<-unique(c(dat$Name1,dat$Name2))
huvac<-huvac[grep("SWINE",huvac,invert=TRUE)]

# ===== Are these variant human cases?

huvac<-huvac[grep("A/OHIO/9/2015",huvac,invert=TRUE)]
huvac<-huvac[grep("A/MINNESOTA/45/2016",huvac,invert=TRUE)]
huvac<-huvac[grep("A/MEXICO/4108/2009",huvac,invert=TRUE)]
```


```{r}
# ===== Move Human Vaccine strains to the left

left<-subset(dat,Name1 %in% huvac)
right<-subset(dat,Name2 %in% huvac)
left
right
right$temp<-right$Name1
right
right$Name1<-right$Name2
right
right$Name2<-right$temp
right
right$temp<-NULL
cdat<-rbind(left,right)
#View(cdat)
#unique(cdat$Name2)

```

```{r}

dat<-cdat[grep("SWINE",cdat$Name2),]
dat<-rbind(dat,cdat[grep("OHIO/9/2015",cdat$Name2),]) 
dat<-rbind(dat,cdat[grep("A/MINNESOTA/45/2016",cdat$Name2),]) 
dat<-rbind(dat,cdat[grep("A/MEXICO/4108/2009",cdat$Name2),]) 
unique(dat$Name2)

dat <- subset(dat, !(Name1 == "A/SOLOMON_ISLANDS/3/2006 E2/M1"))
```

```{r}
# ===== Clean up Human Vaccine names
dat$human_vaccine=dat$Name1
dat$human_vaccine<-unlist(lapply(strsplit(dat$human_vaccine, " MDCK"),'[[',1))
dat$human_vaccine<-unlist(lapply(strsplit(dat$human_vaccine, " E"),'[[',1))
dat$human_vaccine<-unlist(lapply(strsplit(dat$human_vaccine, " X"),'[[',1))
unique(dat$human_vaccine)

```


```{r}
# ===== Clean up Swine Strain names
dat$strain=dat$Name2
#unique(dat$strain)

dat$strain<-unlist(lapply(strsplit(dat$strain, " MDCK"),'[[',1)) # Drop MDCK info
dat$strain<-unlist(lapply(strsplit(dat$strain, " E"),'[[',1))    # Drop E info
sort(unique(dat$strain))
dat
```

```{r}


# Select columns to retain 
dat <- dat[,c("human_vaccine", "strain", "distance")]

#read in metadata
md <- read_delim("annotations-for-agdist-editalphas-nov2021.txt", delim = "\t")
md
#merge with distance dataframe
sdat <- merge(dat, md, by= "strain")

#head(sdat)
# ===== Add HuVac Year, Strain Isolation Year, and Country

sdat$vaccine_year<-substr(sdat$human_vaccine,nchar(sdat$human_vaccine)-3,nchar(sdat$human_vaccine))
#sdat$StrainYear<-substr(sdat$strain,nchar(sdat$strain)-3,nchar(sdat$strain))

# ===== Reorder human vaccine according to year, aka reorder the human vaccines on the x axis
resetorder<-distinct(data.frame(huvac=sdat$human_vaccine,year=sdat$vaccine_year))
resetorder<-resetorder$huvac[order(resetorder$year)]
#resetorder
sdat$human_vaccine<-factor(sdat$human_vaccine,levels=resetorder)


unique(sdat$strain)
head(sdat)
unique(sdat$global_lineage)
sdat <- subset(sdat, !(strain == "A/MEXICO/4108/2009"))
sdat2 <- subset(sdat, !(strain_year == 2011))
```

```{r}

head(sdat2)
#sdat <- sdat[sdat$vaccine_year > 1998,]
sdat_alpha <- sdat2[sdat2$group == "alpha",]
sdat_gn <- sdat2[sdat2$group == "gamma-npdm",]
sdat_deltas <- sdat2[sdat2$group == "delta",]


#write_delim(sdat_alpha, "sdat_alpha.txt", delim = "\t")
#write_delim(sdat_gn, "sdat_gn.txt", delim = "\t")
#write_delim(sdat_deltas, "sdat_deltas.txt", delim = "\t")
#write_delim(sdat2, "sdat2.txt", delim = "\t")
```

```{r}

# Replace this wieh H1 palettes
H1_palette <- c("1A.1" = "#800080",
"1A.1.1" = "#0099CC",
"1A.1.1.1" = "#0099CC",
"1A.1.1.2" = "#568899",
"1A.1.1.3" = "#0e5a73",
"1A.1.2" = "#33FFFF",
"1A.1.3" = "#6666FF",
"1A.2" = "#CCCCFF",
"1A.3" = "#FF99FF",
"1A.3.1" = "#8000FF",
"1A.3.2" = "#FF33FF",
"1A.3.3" = "#CC00CC",
"1A.3.3.1" = "#004080",
"1A.3.3.2" = "#330066",
"1A.3.3.3" = "#3300FF",
"1B.1" = "#FF9999",
"1B.1.1" = "#CC0033",
"1B.1.2" = "#FF66CC",
"1B.1.2.1" = "#B2478E",
"1B.1.2.2" = "#FF3300",
"1B.1.2.3" = "#FF9933",
"1B.2" = "#996633",
"1B.2.1" = "#CC9900",
"1B.2.2" = "#C48945",
"1B.2.2.1" = "#990066",
"1B.2.2.2" = "#FF6666",
"1C.1" = "#00FF00",
"1C.2" = "#12AD2A",
"1C.2.1" = "#B9FF4D",
"1C.2.2" = "#006600",
"1C.2.3" = "#0FF591",
"alpha" = "#0099CC",
"Avian" = "#666666",
"beta" = "#CCCCFF",
"delta1" = "#C48945",
"delta1a" = "#990066",
"delta1b" = "#FF6666",
"delta2" = "#CC9900",
"gamma" = "#3300FF",
"gamma2" = "#FF33FF",
"gamma2-beta-like" = "#8000FF",
"Human" = "#999999",
"Other_Human_1B.2" = "#996633",
"pandemic" = "#330066",
"hu-vaccine" = "#333333",
"Other-Human" = "#d3d3d3",
"1A.2-3-like" = "#CCCCFF",
"1A.3.3-like" = "#CC00CC",
"delta-like" = "#d3d3d3",
"alpha1" = "#800080",
"hu-seasonal" = "#333333")

#unique(sdat$period)
#sdat$period <- factor(sdat$period, levels = c("pre-2010","2011-15","2016-18"))


               
```

```{r}
sdat2$group <- gsub("alpha", "1A.1.1.x", sdat2$group)
sdat2$group <- gsub("delta", "1B.2.x", sdat2$group)
sdat2$group <- gsub("gamma-npdm", "1A.3.3.x", sdat2$group)
```


```{r}
png(filename = "distance-to-huvac-strains.png", 
    res = 300,
    height = 9*300,
    width = 7.5*300)

(maxy<-max(sdat$distance)+2)
maxy=round(maxy)

(p_all <- ggplot(sdat2,aes(x=human_vaccine,y=distance,group=strain,color=global_lineage, shape = country, linetype = host))+
    geom_line()+
    geom_point(size = 1.5)+
    scale_color_manual(values=H1_palette)+
    scale_y_continuous(breaks=c(0:maxy),labels=c(0:maxy),limits = c(0,maxy))+
    theme_bw()+
    theme(axis.text.x = element_text(angle=45, hjust=1),panel.grid.minor=element_blank(), 
          text=element_text(size=11),
       legend.key.size = unit(1.5, 'lines'))+
    annotate("rect",xmin=1.5, xmax=3.5,ymin=-Inf,ymax=Inf,
             alpha=.08,fill="black")+
    annotate("rect",xmin=6.5, xmax=9.5,ymin=-Inf,ymax=Inf,
             alpha=.08,fill="black")+
    annotate("text",x=1,y=maxy-0.9,label="70s",alpha=0.4, size=3)+
    annotate("text",x=2.5,y=maxy-0.9,label="80s",alpha=0.4, size=3)+
    annotate("text",x=5,y=maxy-0.9,label="90s",alpha=0.4, size=3)+
    annotate("text",x=8,y=maxy-0.9,label="00s",alpha=0.4, size=3)+
    annotate("text",x=10.5,y=maxy-0.9,label="post\npdm",alpha=0.4, size=3)+
    geom_hline(yintercept = 3,linetype="dashed")+
    #geom_point(data=sdat_post2009[sdat_post2009$host == "human-infective", ], size = 6)+
    #geom_line(data=sdat[sdat_post2009$host == "human-infective", ], color = 'black')+
    #annotate("text",x=19,y=15,label="2010s",alpha=0.4)+
    labs(x="Human Vaccine Strains\n",
         y="\nAntigenic Distance (AU)\n",
         color="Lineage",
         shape="\nCountry",
         linetype="\nHost")+
    facet_grid(group ~ strain_window) 
)
dev.off()
```



