---
title: "PlotAntigenicDistances H1"
author: "DV, JC"
date: "02/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ===== Initial Variables
rm(list = ls())
```

```{r}
# ===== libraries
library(ggplot2)
library(readr)       # faster and less error prone than read.csv
library(readxl)      # for people who prefer to load excel files, avoid tsv conversion confusion and bugs
library(tidyverse)   # clean data
library(lubridate)

```


```{r}
# === read in metadata csv file 
md <- read_delim("data/md.csv", delim = ",")
```

```{r}
# === rename columns and split in to two (for later merging with the ag_distances df)
md$ag1 <- md$strain
md$ag2 <- md$strain

md$lineage_ag1 <- md$simple_global_lineage
md$lineage_ag2 <- md$simple_global_lineage

md$host_ag1 <- md$host
md$host_ag2 <- md$host

md$year_ag1 <- md$year
md$year_ag2 <- md$year

lin_ag1 <- md %>% select(ag1, lineage_ag1)
lin_ag2 <- md %>% select(ag2, lineage_ag2)

host_ag1 <- md %>% select(ag1, host_ag1)
host_ag2 <- md %>% select(ag2, host_ag2)

year_ag1 <- md %>% select(ag1, year_ag1)
year_ag2 <- md %>% select(ag2, year_ag2)

lin_ag1
host_ag1
year_ag1 
```

```{r}
# === read in the map distances file 
agdist <- read_delim("data/dist3col-antigenic.csv", delim = ",")
head(agdist)

# === merge the lineage info into the distances df
agdist <- inner_join(agdist, lin_ag1, by = "ag1", all.x =F, all.y = F)
agdist <- inner_join(agdist, host_ag1, by = "ag1", all.x =F, all.y = F)
agdist <- inner_join(agdist, year_ag1, by = "ag1", all.x =F, all.y = F)


agdist <- inner_join(agdist, lin_ag2, by = "ag2", all.x =F, all.y = F)
agdist <- inner_join(agdist, host_ag2, by = "ag2", all.x =F, all.y = F)
agdist <- inner_join(agdist, year_ag2, by = "ag2", all.x =F, all.y = F)


# === make new column with pairs of ags and lineage info
agdist$strainpairs <- paste(agdist$ag1, agdist$ag2, sep = ":")
agdist$linpairs <- paste(agdist$lineage_ag1, agdist$lineage_ag2, sep = ":")
agdist$hostpairs <- paste(agdist$host_ag1, agdist$host_ag2, sep = ":")


agdist <- agdist %>% mutate(yeardiff = abs(year_ag1 - year_ag2))

```

```{r}
# === just keep the pairwise data, discard individual info 
agdistp <- agdist[ ,c("strainpairs", "hostpairs", "linpairs", "yeardiff", "agdistances")]
head(agdistp)
```

```{r}
# === read in the ml distances file (processed .mldist file to have map strain names)
ml <- read_delim("data/dist3col-genetic-ml.csv", delim = ",")

# === ditch the zero values to self 
ml <- ml[ml$mldistances != 0, ]

# === make pairs as we did for ags (both directions, as we don't know which version is in the agdistances df)
ml$pairs1 <- paste(ml$ag1, ml$ag2, sep = ":")
ml$pairs2 <- paste(ml$ag2, ml$ag1, sep = ":")

ml_1 <- ml[, c("pairs1", "mldistances")]
ml_2 <- ml[, c("pairs2", "mldistances")]

# === rename column so it matches the agdistp column name for strainnames
ml_1 <- ml_1 %>% 
  rename(strainpairs = pairs1)
ml_2 <- ml_2 %>% 
  rename(strainpairs = pairs2)

# === merge each set into the agdistp df, so ones missing from ml_1 might be found from ml_2
alldist_ml <- merge(agdistp, ml_1, by= "strainpairs", all.x = TRUE) 
alldist_ml <- merge(agdistp, ml_2, by= "strainpairs", all.x = TRUE)

```

```{r}
# === read in the aa distances file (processed .aadist file to have map strain names)
aa <- read_delim("data/dist3col-genetic-aa.csv", delim = ",")
aa
# === ditch the zero values to self 
aa <- aa[aa$aa_distances != 0, ]

# === make pairs as we did for ags (both directions, as we don't know which version is in the agdistances df)
aa$pairs1 <- paste(aa$ag1, aa$ag2, sep = ":")
aa$pairs2 <- paste(aa$ag2, aa$ag1, sep = ":")

aa_1 <- aa[, c("pairs1", "aa_distances")]
aa_2 <- aa[, c("pairs2", "aa_distances")]

# === rename column so it matches the agdistp column name for strainnames
aa_1 <- aa_1 %>% 
  rename(strainpairs = pairs1)
aa_2 <- aa_2 %>% 
  rename(strainpairs = pairs2)

# === merge each set into the agdistp df, so ones missing from aa_1 might be found from aa_2
alldist_aa <- merge(agdistp, aa_1, by= "strainpairs", all.x = TRUE) 
alldist_aa <- merge(agdistp, aa_2, by= "strainpairs", all.x = TRUE)

```

```{r}
# === read in the nuc distances file (processed .nucdist file to have map strain names)
nuc <- read_delim("data/dist3col-genetic-nuc.csv", delim = ",")
nuc
# === ditch the zero values to self 
nuc <- nuc[nuc$nuc_distances != 0, ]

# === make pairs as we did for ags (both directions, as we don't know which version is in the agdistances df)
nuc$pairs1 <- paste(nuc$ag1, nuc$ag2, sep = ":")
nuc$pairs2 <- paste(nuc$ag2, nuc$ag1, sep = ":")

nuc_1 <- nuc[, c("pairs1", "nuc_distances")]
nuc_2 <- nuc[, c("pairs2", "nuc_distances")]

# === rename column so it matches the agdistp column name for strainnames
nuc_1 <- nuc_1 %>% 
  rename(strainpairs = pairs1)
nuc_2 <- nuc_2 %>% 
  rename(strainpairs = pairs2)

# === merge each set into the agdistp df, so ones missing from nuc_1 might be found from nuc_2
alldist_nuc <- merge(agdistp, nuc_1, by= "strainpairs", all.x = TRUE) 
alldist_nuc <- merge(agdistp, nuc_2, by= "strainpairs", all.x = TRUE)

```

```{r}

n <- alldist_nuc[,c("strainpairs", "nuc_distances")]
a <- alldist_aa[,c("strainpairs", "aa_distances")]

alldist1 <- merge(alldist_ml, n, by = "strainpairs")
alldist <- merge(alldist1, a, by = "strainpairs", all = T)

```

```{r}

alldist$hostpairs <- gsub("hu-variant:swine", "swine:hu-variant",  alldist$hostpairs)
alldist$hostpairs <- gsub("hu-seasonal:swine", "swine:hu-seasonal",  alldist$hostpairs)
alldist$hostpairs <- gsub("hu-seasonal:hu-variant", "hu-variant:hu-seasonal",  alldist$hostpairs)
unique(alldist$hostpairs)


unique(alldist$linpairs)
alldist$linpairs <- gsub("1B:1A", "1A:1B",  alldist$linpairs)




```

```{r}

sw <- c("swine:swine", "swine:hu-variant", "hu-variant:swine", "hu-variant:hu-variant")

sw_and_v_only <- alldist[alldist$hostpairs %in% sw,]
sw_and_v_only

write_csv(sw_and_v_only, "data_for_plotting/swine_variant_distances_by_global_lin.csv")

```

```{r}

```

```{r}

```

